Missing typename
Solving the following compilation error in GCC:
CSVReader.h:824:42: error: dependent-name ‘csv_reader_type:: full_type’ is parsed as a non-type, but instantiation yields a type
         return csv_reader_type::full_type(reader, sep);

Compiler indicated this:
note: say ‘typename csv_reader_type:: full_type’ if a type is meant